### ISSUE TITLE
Moes UFO-R11 - No converter available for 'state' ("ON")

### ISSUE THREAD

**Issue by DKanarsky** [zigbee2mqtt/hassio-zigbee2mqtt#519]
### Description of the issue

After successful connection UFO-R11 the switch control related to the device is created in Homeassistant . But trying to turn on or turn off the switch results in error message in zigbee2mqtt add-on: 

```No converter available for 'state' ("ON")```
or 
```No converter available for 'state' ("OFF")```

The switch control activates learning IR codes. Sending messages using MQTT service works as expected

### Addon version

1.33.0-1

### Platform

Core: core-2023.9.1
Supervisor: supervisor-2023.08.3
Operating System: HassOS 10.5

**Comment by DKanarsky** [comment]
No. My workaround is to use mqtt.publish service according to device documentation [there](https://www.zigbee2mqtt.io/devices/UFO-R11.html#moes-ufo-r11). It worked for me.

**Comment by marspd** [comment]
Thanks for the reply, that's what I did on the end myself.

**Comment by dwellexity** [comment]
This is still an issue. UFO-R11 can not learn codes through home assistant interface. Activating the learning mode directly from z2m web interface works without any issues.

**Comment by Koenkk** [comment]
Could you provide me:
- The debug log when starting z2m and waiting for 15 seconds
- The debug log when triggering this from the z2m frontend.
See [this](https://www.zigbee2mqtt.io/guide/configuration/logging.html) on how to enable debug logging.

**Comment by dwellexity** [comment]
I have attached the log here.
[log.log](https://github.com/user-attachments/files/16096015/log.log)
@Koenkk Thank you for your efforts.

**Comment by Koenkk** [comment]
Fixed the issue!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by dwellexity** [comment]
Thanks @Koenkk. The fix works.
However, there is still an issue. If the learned IR code is a bit too long, the HA web interface doesn't show the full code, which makes the learning process useless. If I go into Zigbee2MQTT web interface, the full code is available there without any need to learn it again.
Is it something that can be solved?

**Comment by Koenkk** [comment]
@dwellexity how long is it? The HA limit is 254 chars.

**Comment by dwellexity** [comment]
@Koenkk I got this for an AC remote - 
`H5YBVQNlAC8MigDgCVUD4AlEBDIIMghEBEQE4AlkFKIGBWQUMghkFOADB0ALwAMTMggvDCEBswUyCCEBPQJEBD0C4AlAGx/gCUQElgGiBkQECAIyCLMFuwKKADIIlgEyCAgCCAI9AgezBZYBVQO7AkA9EaIGPQIIAiEB//81I2QUCAIIAkAPAD1gAQcIArsClgG7AkAJAD2gAQKiBgggA8AHA7sCswVACwO7AqIGQAcJPQIIAj0Coga7AkAHQAMFogY9AggC4AMPgAsBogZAAwIIAj0gAQOiBrsCgEcJCAJGmjUjMgg9Ag==`
It has 312 characters.

**Comment by Koenkk** [comment]
So I don't think this can be solved, as the limit for HA is 254 chars.
